name: My Workflow

on:
  push:
    branches:
      - main

 permission:
     contents: write     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Install dependencies
        run: npm install

      # ... other build steps ...

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0

      -name: set up node environment
       uses: actions/setup-node@v3
       with:
        node-version: '16.x'  
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.EMPAPP}}